sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: mecY5tSnkyRATtiI9DVmhlAbeUbWdQNDzGggFxOMBxwTgCVGby29u3QixQTlTyqSpWONGuGu3fcf87zhhdpGnytV9gP77xdh4oHF193+qxU3Gx1sfvpxwVrEwh0V9MBBgh3CguFZPFl6YSFd9HAXkwW0csJFtja3ceoD99/w6HYv4aTOE2j1y+DRgcXTiXek3pw8j4FJuitv6/11DLCMO1/i7SDWdc7i2hrIbrjG4Ph+xN88gibti6ynvzcWh7KIQ9vOsrHC5VvPpiNkEx+fsqSC6cv0fVS3q/xUj53MxsPop9juUi6+9YNZJmWkBdGLIxlBhkA3tunsdYkKHpwnmlv9fY9B2M5fqBXtdP6Yo06PtQsyjdgxxPYBdoL5Sm/N7xGzjk0WzH3PmCiUFkIqKHYEgWu2GZiq9IlTR8jqvjEuuejD5VjEDKj9MLGsEa6NwZWZ1R1sj/crJ3F8OoaRjuW/5wOT/S7qm8F4qlaMhDxmHxKsTY4ucbXwZgZFZf1Sl2kRqL5XGUmOiXcJsbw1DBPWMdic26IuzuuoueHCBazLX49jXUWd2pKdtENb6X0LmlbDZaCz/xrGWpx0McvT8/QWuzwmuDK8xYRTubTWKp4KUOarKHRWgpQw3vdgYCgx0mNMkmOdR76+2xHh9zJy6QiDwFAHnl3Vt+WVF+2o68g=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Amy-Foster_495
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy